name: Update uBlacklist subcription weekly

on:
  schedule:
    - cron: 0 0 * * 0
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Merge txt
      run: |
        cd tools
        cat ../source/cobaltdisco/Google-Chinese-Results-Blocklist/uBlacklist_subscription.txt ../source/gyli/Blocklist/BLOCKLIST ../source/h-matsuo/uBlacklist-subscription-for-developer/list.txt ../source/iorate/ublacklist-example-subscription/uBlacklist.txt ../source/littleserendipity/uBlacklist-Subscription/blacklist.txt ../source/liubiantao/uBlacklist-Websites/uBlacklist.txt ../source/nonPointer/uBlacklist-Subscription/blacklist.txt ../source/scyrte/uBlacklist-Subscription/blacklist.txt ../source/xNathan/uBlacklist-subscription/blacklist.txt ../source/yangjingchuang/ublacklist-subscription/uBlacklist.txt ../source/YeSilin/uBlacklist/list.txt ../source/add_url.txt > uBlacklist.txt
        go run main.go
        cat -s uBlacklist.txt | sed '/^[[:space:]]*$/d'
        mv uBlacklist.txt ../uBlacklist.txt -f

    - name: Commit files
      env:
          MY_SECRET : ${{secrets.commit_secret}}
      run: |
        git config --local user.name $USER_NAME
        git config --local user.email $USER_EMAIL
        git status
        git add .
        git commit -m "Update source uBlacklist subcription"
        git remote set-url --add --push origin https://$MY_SECRET@github.com/eallion/uBlacklist-subscription-compilation.git
        git push origin master -f
        echo 🤘 Update complete.
